# Generated by Django 5.0.7 on 2024-09-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.FileField(upload_to='public/')),
                ('privado', models.FileField(upload_to='private/')),
            ],
        ),
    ]
